extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_death_plane_layer5_area1_lights;
extern Lights1 castle_inside_dl_bricks_grey_lights;
extern u8 castle_inside_dl_black_16_16_ia8[];
extern u8 castle_inside_dl_stone_bricks_grey_ci4[];
extern u8 castle_inside_dl_stone_bricks_grey_ci4_pal_rgba16[];
extern Vtx castle_inside_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx castle_inside_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx castle_inside_dl_PlatformLg_mesh_layer_1_vtx_0[24];
extern Gfx castle_inside_dl_PlatformLg_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_death_plane_layer5_area1[];
extern Gfx mat_revert_castle_inside_dl_death_plane_layer5_area1[];
extern Gfx mat_castle_inside_dl_bricks_grey[];
extern Gfx mat_revert_castle_inside_dl_bricks_grey[];
extern Gfx castle_inside_dl_Plane_mesh_layer_5[];
extern Gfx castle_inside_dl_PlatformLg_mesh_layer_1[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
